<?php
/**
 * Created by PhpStorm.
 * User: yhy
 * Date: 2019/10/30
 * Time: 21:41
 */

namespace app\common\model;


use think\Controller;
use think\Model;

class Goods extends Model
{
    protected $autoWriteTimestamp=true;
    public function insert($data){
//        $data['create_time']=time();
//        $data['update_time']=time();

        return $this->allowField(true)->save($data);

    }
    public function query()
    {
        return parent::select(); // TODO: Change the autogenerated stub
    }
    public function del($id)
    {
        return $this->where('gid',$id)->delete();
    }
    public function selectupdates($id)
    {
        return $this->field('gname,thumb,mprice,sale,stock,banner,detail,cid,description,norms,brand')->where('gid',$id)->find();
    }
    public function updateedit($data,$id){
        return $this->where('gid',$id)->update($data);
    }

}